export default {
  apps: [
    {
      name: "pushlog-prod",
      script: "./dist/index.js",
      instances: 1,
      exec_mode: "cluster",
      env_file: ".env.production",
      env: {
        NODE_ENV: "production",
        APP_ENV: "production",
        PORT: 3000,
      },
      error_file: "./logs/prod-err.log",
      out_file: "./logs/prod-out.log",
      log_file: "./logs/prod-combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      restart_delay: 4000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "pushlog-staging",
      script: "./dist/index.js",
      instances: 1,
      exec_mode: "cluster",
      env_file: ".env.staging",
      env: {
        NODE_ENV: "production",
        APP_ENV: "staging",
        PORT: 3001,
      },
      error_file: "./logs/staging-err.log",
      out_file: "./logs/staging-out.log",
      log_file: "./logs/staging-combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      restart_delay: 4000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "streaming-stats",
      script: "./target/release/streaming-stats",
      cwd: ".",
      instances: 1,
      autorestart: true,
      env: {
        PORT: "5004",
      },
      env_file: ".env",
      error_file: "./logs/stats-err.log",
      out_file: "./logs/stats-out.log",
    },
  ],
};
